name: initial gha
on: [push]
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: "foo"
        run: |
          echo "foo"
      - name: prep
        run: |
          mv .github/workflows/test.yml.tpl .github/workflows/test.yml
  call-workflow:
    uses: ./.github/workflows/test.yml

